<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.2 (Python 3.8.0 on win32)" generated="20200422 13:02:05.362" rpa="false">
<suite id="s1" name="TCs Valid getToken" source="C:\Users\panruethai.e\PycharmProjects\CWNTEST\mobileId\Tests\TCs_Valid_getToken.robot">
<test id="s1-t1" name="Chaincode API_getToken_Issuer: using ${username} and ${password}">
<status status="FAIL" starttime="20200422 13:02:06.181" endtime="20200422 13:02:06.183" critical="yes">Test case contains no keywords.</status>
</test>
<doc>Suite description</doc>
<status status="FAIL" starttime="20200422 13:02:05.366" endtime="20200422 13:02:06.186"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="TCs Valid getToken">TCs Valid getToken</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200422 13:02:05.868" level="ERROR">Error in file 'C:\Users\panruethai.e\PycharmProjects\CWNTEST\mobileId\Tests\TCs_Valid_getToken.robot': Variable '${TestData_getToken_issuer_Path}' not found.</msg>
<msg timestamp="20200422 13:02:06.141" level="ERROR">Error in file 'C:\Users\panruethai.e\PycharmProjects\CWNTEST\mobileId\ChainCodeAPI\Resources\IssuerMiddleware\keyword_getToken.robot': Importing test library 'HttpLibrary.HTTP' failed: SyntaxError: invalid syntax (__init__.py, line 16)
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\panruethai.e\AppData\Local\Programs\Python\Python38-32\Scripts
  C:\Users\panruethai.e\AppData\Local\Programs\Python\Python38-32\python38.zip
  C:\Users\panruethai.e\AppData\Local\Programs\Python\Python38-32\DLLs
  C:\Users\panruethai.e\AppData\Local\Programs\Python\Python38-32\lib
  C:\Users\panruethai.e\AppData\Local\Programs\Python\Python38-32
  C:\Users\panruethai.e\AppData\Roaming\Python\Python38\site-packages
  C:\Users\panruethai.e\AppData\Local\Programs\Python\Python38-32\lib\site-packages
  C:\Users\panruethai.e\AppData\Local\Programs\Python\Python38-32\lib\site-packages\robotframework_csvlib-1.0.0-py3.8.egg
  C:\Users\panruethai.e\AppData\Local\Programs\Python\Python38-32\lib\site-packages\robotframework_csvlibrary-0.0.2-py3.8.egg
  C:\Users\panruethai.e\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32
  C:\Users\panruethai.e\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32\lib
  C:\Users\panruethai.e\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Pythonwin</msg>
<msg timestamp="20200422 13:02:06.157" level="ERROR">Error in file 'C:\Users\panruethai.e\PycharmProjects\CWNTEST\mobileId\ChainCodeAPI\Resources\IssuerMiddleware\keyword_getToken.robot': Importing test library 'CSVLibrary' failed: ModuleNotFoundError: No module named 'version'
Traceback (most recent call last):
  File "&lt;frozen zipimport&gt;", line 259, in load_module
  File "C:\Users\panruethai.e\AppData\Local\Programs\Python\Python38-32\lib\site-packages\robotframework_csvlibrary-0.0.2-py3.8.egg\CSVLibrary\__init__.py", line 3, in &lt;module&gt;
    from version import VERSION
PYTHONPATH:
  C:\Users\panruethai.e\AppData\Local\Programs\Python\Python38-32\Scripts
  C:\Users\panruethai.e\AppData\Local\Programs\Python\Python38-32\python38.zip
  C:\Users\panruethai.e\AppData\Local\Programs\Python\Python38-32\DLLs
  C:\Users\panruethai.e\AppData\Local\Programs\Python\Python38-32\lib
  C:\Users\panruethai.e\AppData\Local\Programs\Python\Python38-32
  C:\Users\panruethai.e\AppData\Roaming\Python\Python38\site-packages
  C:\Users\panruethai.e\AppData\Local\Programs\Python\Python38-32\lib\site-packages
  C:\Users\panruethai.e\AppData\Local\Programs\Python\Python38-32\lib\site-packages\robotframework_csvlib-1.0.0-py3.8.egg
  C:\Users\panruethai.e\AppData\Local\Programs\Python\Python38-32\lib\site-packages\robotframework_csvlibrary-0.0.2-py3.8.egg
  C:\Users\panruethai.e\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32
  C:\Users\panruethai.e\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32\lib
  C:\Users\panruethai.e\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Pythonwin</msg>
</errors>
</robot>
