<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.2 (Python 3.8.2 on win32)" generated="20200412 23:55:11.131" rpa="false">
<suite id="s1" name="RegisterMobileId" source="C:\Users\Strezzo06-PC\PycharmProjects\CWNTEST\mobileId\Tests\RegisterMobileId.robot">
<test id="s1-t1" name="Register 1 mobileId Successfully">
<kw name="Send Request getToken" library="keyword_getToken">
<kw name="Create Session" library="RequestsLibrary">
<doc>Create Session: create a HTTP session to a server</doc>
<arguments>
<arg>getTokenSS</arg>
<arg>${base_url}</arg>
</arguments>
<msg timestamp="20200412 23:55:11.409" level="INFO">Creating Session using : alias=getTokenSS, url=http://172.16.24.55:3216, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" starttime="20200412 23:55:11.409" endtime="20200412 23:55:11.409"></status>
</kw>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>username=${username}</arg>
<arg>password=${password}</arg>
</arguments>
<assign>
<var>${body}</var>
</assign>
<msg timestamp="20200412 23:55:11.409" level="INFO">${body} = {'username': '001', 'password': 'secret'}</msg>
<status status="PASS" starttime="20200412 23:55:11.409" endtime="20200412 23:55:11.409"></status>
</kw>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>Content-Type=application/json</arg>
</arguments>
<assign>
<var>${header}</var>
</assign>
<msg timestamp="20200412 23:55:11.409" level="INFO">${header} = {'Content-Type': 'application/json'}</msg>
<status status="PASS" starttime="20200412 23:55:11.409" endtime="20200412 23:55:11.409"></status>
</kw>
<kw name="Post Request" library="RequestsLibrary">
<doc>Send a POST request on the session object found using the
given `alias`</doc>
<arguments>
<arg>getTokenSS</arg>
<arg>${url_getToken_issuer_MDW}</arg>
<arg>data=${body}</arg>
<arg>headers=${header}</arg>
</arguments>
<assign>
<var>${response}</var>
</assign>
<msg timestamp="20200412 23:55:11.409" level="INFO">POST Request using : uri=/token, params=None, files=None, allow_redirects=True, timeout=None
headers={'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'application/json'} 
data={"username": "001", "password": "secret"} 
json=None</msg>
<msg timestamp="20200412 23:55:32.458" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x046C9F40&gt;: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')': /token</msg>
<msg timestamp="20200412 23:55:53.691" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x046C92B0&gt;: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')': /token</msg>
<msg timestamp="20200412 23:56:15.124" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x046C9A18&gt;: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')': /token</msg>
<msg timestamp="20200412 23:56:36.131" level="FAIL">ConnectionError: HTTPConnectionPool(host='172.16.24.55', port=3216): Max retries exceeded with url: /token (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0470D070&gt;: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))</msg>
<status status="FAIL" starttime="20200412 23:55:11.409" endtime="20200412 23:56:36.131"></status>
</kw>
<status status="FAIL" starttime="20200412 23:55:11.409" endtime="20200412 23:56:36.132"></status>
</kw>
<status status="FAIL" starttime="20200412 23:55:11.409" endtime="20200412 23:56:36.132" critical="yes">ConnectionError: HTTPConnectionPool(host='172.16.24.55', port=3216): Max retries exceeded with url: /token (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0470D070&gt;: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))</status>
</test>
<doc>Suite description</doc>
<status status="FAIL" starttime="20200412 23:55:11.132" endtime="20200412 23:56:36.136"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="RegisterMobileId">RegisterMobileId</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200412 23:55:11.166" level="ERROR">Error in file 'C:\Users\Strezzo06-PC\PycharmProjects\CWNTEST\mobileId\ChainCodeAPI\Resources\Issuer\keyword_getToken.robot': Importing test library 'REST' failed: ModuleNotFoundError: No module named 'REST'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\Strezzo06-PC\AppData\Local\Programs\Python\Python38-32\Scripts\robot.exe
  c:\users\strezzo06-pc\appdata\local\programs\python\python38-32\python38.zip
  c:\users\strezzo06-pc\appdata\local\programs\python\python38-32\DLLs
  c:\users\strezzo06-pc\appdata\local\programs\python\python38-32\lib
  c:\users\strezzo06-pc\appdata\local\programs\python\python38-32
  c:\users\strezzo06-pc\appdata\local\programs\python\python38-32\lib\site-packages</msg>
<msg timestamp="20200412 23:55:11.409" level="ERROR">Error in file 'C:\Users\Strezzo06-PC\PycharmProjects\CWNTEST\mobileId\ChainCodeAPI\Resources\Issuer\keyword_getToken.robot': Importing test library 'HttpLibrary.HTTP' failed: ModuleNotFoundError: No module named 'HttpLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\Strezzo06-PC\AppData\Local\Programs\Python\Python38-32\Scripts\robot.exe
  c:\users\strezzo06-pc\appdata\local\programs\python\python38-32\python38.zip
  c:\users\strezzo06-pc\appdata\local\programs\python\python38-32\DLLs
  c:\users\strezzo06-pc\appdata\local\programs\python\python38-32\lib
  c:\users\strezzo06-pc\appdata\local\programs\python\python38-32
  c:\users\strezzo06-pc\appdata\local\programs\python\python38-32\lib\site-packages</msg>
<msg timestamp="20200412 23:55:32.458" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x046C9F40&gt;: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')': /token</msg>
<msg timestamp="20200412 23:55:53.691" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x046C92B0&gt;: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')': /token</msg>
<msg timestamp="20200412 23:56:15.124" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x046C9A18&gt;: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')': /token</msg>
</errors>
</robot>
